# config for analysis

# conda environment file
environment: environment.yml

# most CPUs to ever use at once
max_cpus: 8

# amplicons sequenced by PacBio
amplicons_Wuhan_Hu_1: data/PacBio_amplicon_Wuhan_Hu_1.gb
amplicons_BA1: data/PacBio_amplicon_BA1.gb
amplicons_BA2: data/PacBio_amplicon_BA2.gb

# how to parse the amplicon
feature_parse_specs_Wuhan_Hu_1: data/feature_parse_specs_Wuhan_Hu_1.yaml
feature_parse_specs_BA1: data/feature_parse_specs_BA1.yaml
feature_parse_specs_BA2: data/feature_parse_specs_BA2.yaml

# do we get the sequencing data from the 'HutchServer' or 'SRA'?
seqdata_source: HutchServer

# list of PacBio sequencing runs linking barcodes to variants
pacbio_runs: data/PacBio_runs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering

# pdbs for mapping, analysis
pdb_6m0j: data/6m0j.pdb
pdb_WH1: data/VOC_structures/split_and_aligned/RBD_WH1_6m0j.pdb
pdb_N501Y: data/VOC_structures/split_and_aligned/RBD_alpha1_7ekf.pdb
pdb_beta1: data/VOC_structures/split_and_aligned/RBD_beta1_7ekg.pdb
pdb_beta2: data/VOC_structures/split_and_aligned/RBD_beta2.pdb
pdb_beta3: data/VOC_structures/split_and_aligned/RBD_beta3.pdb
pdb_delta1: data/VOC_structures/split_and_aligned/RBD_delta1_7wbq.pdb
pdb_delta2: data/VOC_structures/split_and_aligned/RBD_delta2_7wbq.pdb
pdb_omicron1: data/VOC_structures/split_and_aligned/RBD_omicron1.pdb
pdb_omicron2: data/VOC_structures/split_and_aligned/RBD_omicron2.pdb
pdb_omicron3: data/VOC_structures/split_and_aligned/RBD_omicron3_7wbp.pdb

pdb_WH1_ACE2: data/VOC_structures/split_and_aligned/ACE2_WH1_6m0j.pdb
pdb_N501Y_ACE2: data/VOC_structures/split_and_aligned/ACE2_alpha1_7ekf.pdb
pdb_beta1_ACE2: data/VOC_structures/split_and_aligned/ACE2_beta1_7ekg.pdb
pdb_beta2_ACE2: data/VOC_structures/split_and_aligned/ACE2_beta2.pdb
pdb_beta3_ACE2: data/VOC_structures/split_and_aligned/ACE2_beta3.pdb
pdb_delta1_ACE2: data/VOC_structures/split_and_aligned/ACE2_delta1_7wbq.pdb
pdb_delta2_ACE2: data/VOC_structures/split_and_aligned/ACE2_delta2_7wbq.pdb
pdb_omicron1_ACE2: data/VOC_structures/split_and_aligned/ACE2_omicron1.pdb
pdb_omicron2_ACE2: data/VOC_structures/split_and_aligned/ACE2_omicron2.pdb
pdb_omicron3_ACE2: data/VOC_structures/split_and_aligned/ACE2_omicron3_7wbp.pdb

pdb_WH1_cryo: data/VOC_structures/cryo/WH1_7kmb.pdb
pdb_alpha_cryo: data/VOC_structures/cryo/alpha_7mjn.pdb
pdb_beta_cryo: data/VOC_structures/cryo/beta_7vx4.pdb
pdb_delta_cryo: data/VOC_structures/cryo/delta_7v8b.pdb


# URLs from which we download binding & expression of mutants & variants and surveillance count data
mut_bind_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS/master/results/single_mut_effects/single_mut_effects.csv
VOC_mut_bind_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS_variants/main/results/final_variant_scores/final_variant_scores.csv
mut_antibody_escape_url: https://media.githubusercontent.com/media/jbloomlab/SARS2_RBD_Ab_escape_maps/main/processed_data/escape_data.csv
mut_clade_occurrence_url: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-DMS-evolution/main/results/RBD_mut_counts/RBD_mutation_counts.csv?token=GHSAT0AAAAAABXD2PZJ3IUUD666A2XU2LL4YXJWVOQ


# output directories / files
summary_dir: results/summary
mut_bind_expr: results/prior_DMS_data/mutant_ACE2binding_expression.csv
VOC_mut_bind_expr: results/prior_DMS_data/VOC_mutant_ACE2binding_expression.csv
mut_antibody_escape: results/prior_DMS_data/mutant_antibody-escape.csv
mut_clade_occurrence: results/prior_DMS_data/mutant_clade_occurrence.csv
figs_dir: results/figures
ccs_dir: results/ccs
process_ccs_dir: results/process_ccs
processed_ccs_file_Wuhan_Hu_1: results/process_ccs/processed_ccs_Wuhan_Hu_1.csv
processed_ccs_file_BA1: results/process_ccs/processed_ccs_BA1.csv
processed_ccs_file_BA2: results/process_ccs/processed_ccs_BA2.csv
variants_dir: results/variants
nt_variant_table_file_Wuhan_Hu_1: results/variants/nucleotide_variant_table_Wuhan_Hu_1.csv
nt_variant_table_file_BA1: results/variants/nucleotide_variant_table_BA1.csv
nt_variant_table_file_BA2: results/variants/nucleotide_variant_table_BA2.csv
codon_variant_table_file_Wuhan_Hu_1: results/variants/codon_variant_table_Wuhan_Hu_1.csv
codon_variant_table_file_BA1: results/variants/codon_variant_table_BA1.csv
codon_variant_table_file_BA2: results/variants/codon_variant_table_BA2.csv
counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv
expression_sortseq_dir: results/expression_meanF
expression_sortseq_file: results/expression_meanF/bc_expression.csv
Titeseq_Kds_dir: results/binding_Kd
Titeseq_Kds_file: results/binding_Kd/bc_binding.csv
final_variant_scores_dir: results/final_variant_scores
final_variant_scores_mut_file: results/final_variant_scores/final_variant_scores.csv
epistatic_shifts_dir: results/epistatic_shifts
JSD_v_WH1_file: results/epistatic_shifts/JSD_versus_Wuhan1_by_target.csv
JSD_v_WH1_expr_file: results/epistatic_shifts/JSD_versus_Wuhan1_EXPRESSION_by_target.csv
visualization_dir: docs/_includes


# parameters for running PacBio `ccs` program
min_ccs_accuracy: 0.999
min_ccs_passes: 3
min_ccs_length: 50
max_ccs_length: 5000

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0

# Input files for analyses from the data subdirectory
RBD_sites: data/RBD_sites.csv
